### ISSUE TITLE
Better filetype & auxtype support

### ISSUE THREAD

**Issue by JohnMBrooks** [mach-kernel/cadius#4]
Ideally retain filetype & auxtype between Mac OS files & ProDOS

And/or allow explicit filetype and auxtype suffix:
PRODOS#FF0000
BIN.AT.2000#062000

-JB
@JBrooksBSI

**Comment by mach-kernel** [comment]
I think the latter might be a more elegant solution since I think that attempting file kind translations on other systems (e.g. Linux, Windows) might be an exercise, and namely it would be great if we provided a consistent expectation for how Cadius works everywhere. Does the latter sit well with you? 🦄
